using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Tracks.Model
{

    public class Song
    {
        public string Title { get; set; }
    }

    public class Track
    {
        [BsonId]
        public ObjectId InternalId { get; set; }                // standard BSonId generated by MongoDb
        public string Id { get; set; }                          // external Id, easier to reference: 1,2,3 etc. 
        public ICollection<Song> Tracks { get; set; }
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}
